
tasks:
  - init: mvn package -DskipTests

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - redhat.fabric8-analytics
    - redhat.vscode-commons
    - asciidoctor.asciidoctor-vscode
