name: maven build on pr

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
