name: Deploy (Push)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SAFE_BRANCH_NAME=${BRANCH_NAME//\//-}
          mvn --batch-mode --update-snapshots -Drevision=${SAFE_BRANCH_NAME}-SNAPSHOT deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
