name: Verify (Push)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        archunit-version: ['1.4.1']
        java: [ '11', '17', '21', '25' ]
        
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          SAFE_BRANCH_NAME=${BRANCH_NAME//\//-}
          mvn --batch-mode --update-snapshots -Drevision=${SAFE_BRANCH_NAME}-SNAPSHOT verify -Darchunit.version=${{ matrix.archunit-version }}
